
export const COLORS = {
  deepSlate: '#0f172a',
  midnightBlue: '#1e1b4b',
  neonCyan: '#38bdf8',
  electricViolet: '#8b5cf6',
  antiqueGold: '#f59e0b',
  paperCream: '#fef3c7',
  charcoal: '#334155',
  mint: '#34d399',
  errorRed: '#ef4444'
};

export const DEFAULT_CONFIG = {
  examName: 'Final Examination',
  subtitle: 'Generated by Study.AI',
  studentNamePlaceholder: true,
  watermarkText: 'CONFIDENTIAL',
  watermarkOpacity: 0.1,
  mcqCount: 5,
  shortCount: 3,
  essayCount: 1,
  longAnswerCount: 1,
  tfCount: 0,
  fillCount: 0,
  matchingCount: 0,
  difficulty: 'Medium',
  topicFocus: '',
  headerFontSize: 24,
  showLogo: true,
  pdfFontTheme: 'Classic'
};

export const APP_ACCESS_CODE = 'mattafarid1184';