
import { ExamConfig, Question, QuestionType } from '../types';

export const generatePDF = (questions: Question[], config: ExamConfig) => {
  const { jspdf } = window;
  if (!jspdf) { console.error("jsPDF not loaded"); return; }

  const doc = new jspdf.jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let cursorY = 20;

  // Font Configuration based on Theme
  const setHeaderFont = () => {
    if (config.pdfFontTheme === 'Modern') doc.setFont("helvetica", "bold");
    else if (config.pdfFontTheme === 'Elegant') doc.setFont("times", "bold");
    else doc.setFont("helvetica", "bold"); // Classic default
  };

  const setBodyFont = () => {
    if (config.pdfFontTheme === 'Modern') doc.setFont("helvetica", "normal");
    else doc.setFont("times", "normal"); // Classic & Elegant use Serif for body
  };

  const setBodyItalic = () => {
    if (config.pdfFontTheme === 'Modern') doc.setFont("helvetica", "italic");
    else doc.setFont("times", "italic");
  };

  // --- Helpers ---
  const drawLogo = (x: number, y: number, size: number) => {
    // High-Fidelity Vector Drawing of Study.AI Reactor Logo
    const cyan = [34, 211, 238];
    const purple = [168, 85, 247];
    
    // Outer Ring (Tech segments)
    doc.setDrawColor(cyan[0], cyan[1], cyan[2]);
    doc.setLineWidth(0.4);
    doc.circle(x, y, size, 'S');
    
    // Inner Ring (Purple Offset)
    doc.setDrawColor(purple[0], purple[1], purple[2]);
    doc.circle(x, y, size * 0.7, 'S');
    
    // Core Circuitry (Cross)
    doc.setDrawColor(cyan[0], cyan[1], cyan[2]);
    doc.line(x - size*0.4, y, x + size*0.4, y);
    doc.line(x, y - size*0.4, x, y + size*0.4);

    // Central Node (Filled)
    doc.setFillColor(cyan[0], cyan[1], cyan[2]);
    doc.circle(x, y, size * 0.25, 'F');
    
    // Lightning Bolt / Spark
    doc.setFillColor(255, 255, 255);
    const s = size * 0.12;
    doc.triangle(x - s, y - s, x + s, y - s, x, y + s*1.5, 'F');
  };

  const addWatermark = () => {
    if (config.watermarkText) {
      doc.saveGraphicsState();
      doc.setTextColor(200, 200, 200);
      doc.setFontSize(50);
      setHeaderFont(); // Use header font for watermark
      doc.setGState(new doc.GState({ opacity: config.watermarkOpacity }));
      
      // Center the watermark
      doc.text(config.watermarkText, pageWidth / 2, pageHeight / 2, { align: 'center', angle: 45 });
      doc.restoreGraphicsState();
    }
  };

  const addHeader = () => {
    addWatermark();
    
    let titleY = margin + 15;
    
    // Logo Rendering
    if (config.showLogo) {
       drawLogo(margin + 10, margin + 12, 9);
    }

    // Title Section
    setHeaderFont();
    doc.setFontSize(config.headerFontSize || 24);
    doc.setTextColor(0, 0, 0);
    doc.text(config.examName.toUpperCase(), pageWidth / 2, titleY, { align: "center" });
    
    setBodyItalic();
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.text(config.subtitle || "Generated by Study.AI", pageWidth / 2, titleY + 8, { align: "center" });

    // Decorative Line
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(margin, titleY + 15, pageWidth - margin, titleY + 15);

    // Student Details
    if (config.studentNamePlaceholder) {
      const detailsY = titleY + 28;
      setHeaderFont();
      doc.setFontSize(11);
      doc.setTextColor(0);
      
      doc.text("Name: __________________________________", margin, detailsY);
      doc.text("Roll No: __________________", pageWidth - margin - 50, detailsY);
      
      doc.text("Date: _______________", margin, detailsY + 10);
      doc.text("Max Marks: 100", pageWidth - margin - 50, detailsY + 10);
      
      doc.line(margin, detailsY + 18, pageWidth - margin, detailsY + 18);
      cursorY = detailsY + 30;
    } else {
      cursorY = titleY + 25;
    }
  };

  const addFooter = (pageNo: number, total: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    doc.text(`Page ${pageNo} of ${total}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    doc.text("Study.AI - Assessment System", margin, pageHeight - 10);
  };

  const checkPageBreak = (heightNeeded: number) => {
    if (cursorY + heightNeeded > pageHeight - margin) {
      doc.addPage();
      addWatermark();
      cursorY = margin + 10;
    }
  };

  addHeader();

  // --- Content Generation ---
  const grouped = questions.reduce((acc, q) => {
    if (!acc[q.type]) acc[q.type] = [];
    acc[q.type].push(q);
    return acc;
  }, {} as Record<QuestionType, Question[]>);

  const sections = [
    { type: QuestionType.MCQ, title: "Section A: Multiple Choice Questions" },
    { type: QuestionType.TRUE_FALSE, title: "Section B: True or False" },
    { type: QuestionType.MATCHING, title: "Section C: Matching" },
    { type: QuestionType.FILL_BLANK, title: "Section D: Fill in the Blanks" },
    { type: QuestionType.SHORT_ANSWER, title: "Section E: Short Answer Questions" },
    { type: QuestionType.LONG_ANSWER, title: "Section F: Detailed Answer Questions" },
    { type: QuestionType.ESSAY, title: "Section G: Essay" },
  ];

  sections.forEach((sec) => {
    const qs = grouped[sec.type];
    if (!qs || qs.length === 0) return;

    checkPageBreak(25);
    
    // Section Header
    doc.setFillColor(245, 247, 250); 
    doc.setDrawColor(220);
    doc.rect(margin, cursorY, pageWidth - (margin * 2), 10, 'F');
    
    setHeaderFont();
    doc.setFontSize(11);
    doc.setTextColor(30);
    doc.text(sec.title.toUpperCase(), margin + 5, cursorY + 7);
    cursorY += 18;

    qs.forEach((q, idx) => {
      setBodyFont();
      doc.setFontSize(12);
      doc.setTextColor(0);

      const qText = `${idx + 1}. ${q.question}`;
      const splitText = doc.splitTextToSize(qText, pageWidth - (margin * 2) - 5);
      const textH = splitText.length * 6; // Standard spacing
      
      let extraH = 8;
      if (sec.type === QuestionType.MCQ && q.options) extraH += q.options.length * 6;
      if (sec.type === QuestionType.MATCHING && q.pairs) extraH += q.pairs.length * 6 + 5;
      if (sec.type === QuestionType.SHORT_ANSWER) extraH += 30;
      if (sec.type === QuestionType.LONG_ANSWER) extraH += 70;
      if (sec.type === QuestionType.ESSAY) extraH += 110;

      checkPageBreak(textH + extraH);

      doc.text(splitText, margin, cursorY);
      cursorY += textH + 2;

      if (sec.type === QuestionType.MCQ && q.options) {
        setBodyFont();
        doc.setFontSize(11);
        q.options.forEach((opt, i) => {
           doc.text(`   (${String.fromCharCode(97+i)}) ${opt}`, margin + 5, cursorY);
           cursorY += 6;
        });
        cursorY += 4;
      }
      else if (sec.type === QuestionType.MATCHING && q.pairs) {
         doc.setFontSize(11);
         const rightX = pageWidth / 2 + 10;
         const shuffledRight = [...q.pairs].map(p => p.right).sort(() => Math.random() - 0.5);
         
         setHeaderFont();
         doc.text("Column A", margin + 5, cursorY);
         doc.text("Column B", rightX, cursorY);
         cursorY += 6;
         setBodyFont();

         q.pairs.forEach((p, i) => {
            doc.text(`${i+1}. ${p.left}`, margin + 5, cursorY);
            doc.text(`${String.fromCharCode(65+i)}. ${shuffledRight[i]}`, rightX, cursorY);
            cursorY += 6;
         });
         cursorY += 4;
      }
      else if (['SHORT_ANSWER', 'LONG_ANSWER', 'ESSAY'].includes(sec.type)) {
         const lines = Math.floor((extraH - 12) / 8);
         doc.setDrawColor(220);
         doc.setLineWidth(0.1);
         for(let l=0; l<lines; l++) {
             doc.line(margin, cursorY + (l*8), pageWidth-margin, cursorY + (l*8));
         }
         cursorY += (lines*8) + 8;
      }

      cursorY += 4;
    });
    cursorY += 5;
  });

  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  doc.save(`${config.examName.replace(/\s+/g, '_')}_StudyAI.pdf`);
};

export const generateAnswerKey = (questions: Question[], config: ExamConfig) => {
    const { jspdf } = window;
    if (!jspdf) return;
    const doc = new jspdf.jsPDF();
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(`ANSWER KEY: ${config.examName}`, 20, 20);
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);
    
    let cursorY = 35;
    questions.forEach((q, idx) => {
        if(cursorY > 270) { doc.addPage(); cursorY = 20; }
        
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(`Q${idx + 1} (${q.type}):`, 20, cursorY);
        
        doc.setFont("times", "normal");
        let ansText = q.answer || "Check Grading Rubric";
        
        if(q.type === 'MATCHING' && q.pairs) {
           ansText = q.pairs.map((p,i) => `${i+1} -> ${p.right}`).join(';  ');
        }
        
        const split = doc.splitTextToSize(ansText, 140);
        doc.text(split, 60, cursorY);
        
        cursorY += (split.length * 6) + 4;
    });
    doc.save(`${config.examName}_KEY.pdf`);
};
